name: CI Test

on:
  workflow_dispatch:


jobs:
  ci:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 'Check out repository'
      - name: 'Echo git version'
        run: |
          echo $(git describe --long --dirty --always --tags)
      - name: 'Echo git branch'
        run: |
          echo ${GITHUB_REF##*/}
      - run: mkdir -p build

      - name: Generate Badges
        uses: jaywcjlove/generated-badges@main
        with:
          label: version
          status: v1.0.2
          output: .github/workflows/badges/cyan.svg
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '.github/workflows/badges/'
